server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:~/dbname;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
        ddl-auto: update        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          format_sql: true      # 쿼리 로그 포맷 (정렬)
          show_sql: true        # 쿼리 로그 출력

logging:
  level:
    root: INFO
